remote_theme: PaulSt/eleven
theme: eleven-theme

eleven:
  date_format: "%b %d, %Y"
  logo:  "assets/logo.png" 

permalink: post/:title

title: "eleven"
description: "simple & clean jekyll theme"
excerpt_separator: <!--more-->
page_excerpts: true

collections:
  examplecollection:
    output: true
    title: "Collections"

# for github subpage
baseurl: /eleven
