name: ci

on:
  push:
    branches: [main]
  pull_request:
    branches: ['main**']
  release:
    types: [created]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:     
    - uses: actions/checkout@v2
      with: 
        fetch-depth: 0
    - run: gem build 

  publish:
    runs-on: ubuntu-latest
    if: github.event_name == 'release' && github.event.action == 'created' 
    steps:
    - uses: actions/checkout@v2
      with: 
        fetch-depth: 0
    - name: Build and publish gem
      uses: jstastny/publish-gem-to-github@master
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        owner: PaulSt
