name: ci

on:
  push:
    branches: [main]
  pull_request:
    branches: ['main**']
  release:
    types: [created]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:     
    - uses: actions/checkout@v2
      with: 
        fetch-depth: 0
    - run: gem build 
    - name: setup credentials 
      if: github.event_name == 'release' && github.event.action == 'created' 
      run: |
          mkdir -p ~/.gem
          cat << EOF > ~/.gem/credentials
          ---
          :github: Bearer ${{ secrets.GITHUB_TOKEN }}
          :rubygems_api_key: ${{ secrets.RUBY }}
          EOF
          chmod 0600 ~/.gem/credentials
    - run: gem push *.gem 
      if: github.event_name == 'release' && github.event.action == 'created' 


  github-pages:
    runs-on: ubuntu-latest
    if: github.event_name == 'release' && github.event.action == 'created' 
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - uses: helaili/jekyll-action@v2
        with:                               
          token: ${{ secrets.GITHUB_TOKEN }}
          target_branch: 'gh-pages'
