name: ci

on:
  push:
    branches: [main]
  pull_request:
    branches: ['main**']
  release:
    types: [created]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:     
    - uses: actions/checkout@v2
    - run: gem build 

  #publish:
    #needs: [ubuntu,macos]
    #runs-on: ubuntu-latest
    #if: github.event_name == 'release' && github.event.action == 'created' 
    #steps:
